# Generated by Django 3.1.1 on 2020-10-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201002_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.AddField(
            model_name='car',
            name='color_type',
            field=models.IntegerField(choices=[(0, 'WHITE'), (1, 'RED'), (2, 'BLACK'), (3, 'BLUE'), (4, 'YELLOW'), (5, 'GREEN'), (6, 'GREY'), (7, 'ORANGE')], default=0, verbose_name='Color'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_city', to='api.country', verbose_name='Country')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city_car', to='api.city', verbose_name='City'),
        ),
    ]
