# Generated by Django 3.1.1 on 2020-11-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201123_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(null=True, upload_to='cars'),
        ),
    ]
