# Generated by Django 3.1.1 on 2020-11-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_car_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photo',
        ),
        migrations.AddField(
            model_name='model',
            name='photo',
            field=models.ImageField(null=True, upload_to='models'),
        ),
    ]
